server:
  port: 8082
  servlet:
    context-path: /company

# jpa config
spring:
  application:
    name: user-service
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/stock_market?characterEncoding=UTF8&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

#eureka:
#  client:
#    registryFetchIntervalSeconds: 5
#    service-url:
#      defaultZone: http://127.0.0.1:8761/eureka/
#  instance:
#    leaseRenewalIntervalInSeconds: 10
#    health-check-url-path: /actuator/health
#    metadata-map:
#      management:
#        context-path: /user/actuator
#    health-check-url: http://127.0.0.1:${server.port}/user/actuator/health
#    status-page-url: http://127.0.0.1:${server.port}/user/actuator/info
#    home-page-url: http://127.0.0.1:${server.port}/

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 30000

ribbon:
  ReadTimeout: 30000
  ConnectTimeout: 30000

feign:
  hystrix:
    enabled: true